### ISSUE TITLE
Get CORS request reject when process image.

### ISSUE THREAD

**Issue by phongloihong** [GetStream/stream-js#233]
Hi.
When I upload an image everything work perfect and then I use response URL to process the image and get this error:

```javascript
Error: Error: CORS request rejected: https://cloud-api.stream-io-api.com/api/v1.0/images/https://stream-cloud-uploads.imgix.net/images/43505/f0fb7a72-af50-4ca6-95c0-81241640562d.go-logo.png?s=9c6751325417c19bc361c9b5cd1517fd&h=800&w=418&resize=clip&api_key=yqdk4535avyb&location=unspecified
    at StreamApiError.ErrorAbstract (webpack-internal:///./node_modules/getstream/lib/lib/errors.js:18:11)
    at new StreamApiError (webpack-internal:///./node_modules/getstream/lib/lib/errors.js:84:17)
    at Object.task [as callback] (webpack-internal:///./node_modules/getstream/lib/lib/client.js:264:16)
    at on_response (webpack-internal:///./node_modules/xmlhttp-request/index.js:319:22)
    at XMLHttpRequest.on_state_change (webpack-internal:///./node_modules/xmlhttp-request/index.js:295:7)
```
how i can fix this ?
thank you for your time.

**Comment by rosskhanas** [comment]
@phongloihong did you find a solution?

**Comment by ferhatelmas** [comment]
this should be fixed by now
