### ISSUE TITLE
Typescript typings for feed.get() are inaccurate

### ISSUE THREAD

**Issue by fnimick** [GetStream/stream-js#251]
The types indicate that the first argument `options` is optional and may be undefined, but the call fails with an error if undefined is provided.

```
/Users/francis/outcomes4me/api/node_modules/getstream/lib/lib/client.js:446
    return this.enrichByDefault || options.ownReactions != null || options.withRecentReactions != null || options.withReactionCounts != null || options.withOwnChildren != null;
                                           ^
TypeError: Cannot read property 'ownReactions' of undefined
    at StreamClient.shouldUseEnrichEndpoint (/Users/francis/outcomes4me/api/node_modules/getstream/lib/lib/client.js:446:44)
    at StreamFeed.get (/Users/francis/outcomes4me/api/node_modules/getstream/lib/lib/feed.js:294:21)
```

The issue is here: https://github.com/GetStream/stream-js/blob/master/types/getstream/index.d.ts#L172

**Comment by mircea-cosbuc** [comment]
This particular issue should be fixed with https://www.npmjs.com/package/getstream/v/4.2.5.
