### ISSUE TITLE
Since v4.5.0 getting Cannot find module '@babel/runtime/helpers/extends'

### ISSUE THREAD

**Issue by scopsy** [GetStream/stream-js#290]
Since v4.5.0 I'm getting the following error on Travis CI build with docker. 
Node.js: 10

`
Error: Cannot find module '@babel/runtime/helpers/extends'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/src/app/node_modules/getstream/lib/lib/client.js:1:78)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/src/app/node_modules/getstream/lib/getstream.js:6:20)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! activityfeedprovider@1.0.0 start: `node dist/app.js`
npm ERR! Exit status 1
npm ERR! 
`

**Comment by ferhatelmas** [comment]
@jaapbakker88 Culprit https://github.com/GetStream/stream-js/pull/276

**Comment by jaapbakker88** [comment]
@scopsy I just released 4.5.1 which should resolve this issue.

**Comment by ferhatelmas** [comment]
https://babeljs.io/docs/en/babel-plugin-transform-runtime#installation

This explains how they should be added for a reference.

@scopsy thanks :heart:
