### ISSUE TITLE
ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by klaszlo8207** [GetStream/stream-js#295]
sometimes I get:

 Error: Error: ESOCKETTIMEDOUT
[2020-04-29 12:26:45]     at StreamApiError.ErrorAbstract (/opt/connect_flutter/node_modules/getstream/lib/lib/errors.js:18:11)
[2020-04-29 12:26:45]     at new StreamApiError (/opt/connect_flutter/node_modules/getstream/lib/lib/errors.js:84:17)
[2020-04-29 12:26:45]     at Request.task [as _callback] (/opt/connect_flutter/node_modules/getstream/lib/lib/client.js:297:16)
[2020-04-29 12:26:45]     at self.callback (/opt/connect_flutter/node_modules/request/request.js:185:22)
[2020-04-29 12:26:45]     at Request.emit (events.js:310:20)
[2020-04-29 12:26:45]     at ClientRequest.<anonymous> (/opt/connect_flutter/node_modules/request/request.js:819:16)
[2020-04-29 12:26:45]     at Object.onceWrapper (events.js:416:28)
[2020-04-29 12:26:45]     at ClientRequest.emit (events.js:310:20)
[2020-04-29 12:26:45]     at TLSSocket.emitRequestTimeout (_http_client.js:714:9)
[2020-04-29 12:26:45]     at Object.onceWrapper (events.js:416:28) {
[2020-04-29 12:26:45]   error: undefined,
[2020-04-29 12:26:45]   response: undefined,
[2020-04-29 12:26:45]   message: Error: ESOCKETTIMEDOUT
[2020-04-29 12:26:45]       at ClientRequest.<anonymous> (/opt/connect_flutter/node_modules/request/request.js:816:19)
[2020-04-29 12:26:45]       at Object.onceWrapper (events.js:416:28)
[2020-04-29 12:26:45]       at ClientRequest.emit (events.js:310:20)
[2020-04-29 12:26:45]       at TLSSocket.emitRequestTimeout (_http_client.js:714:9)
[2020-04-29 12:26:45]       at Object.onceWrapper (events.js:416:28)
[2020-04-29 12:26:45]       at TLSSocket.emit (events.js:310:20)
[2020-04-29 12:26:45]       at TLSSocket.Socket._onTimeout (net.js:479:8)
[2020-04-29 12:26:45]       at listOnTimeout (internal/timers.js:549:17)
[2020-04-29 12:26:45]       at processTimers (internal/timers.js:492:7) {
[2020-04-29 12:26:45]     code: 'ESOCKETTIMEDOUT',
[2020-04-29 12:26:45]     connect: false
[2020-04-29 12:26:45]   }
[2020-04-29 12:26:45] }

and I get the response after 30 seconds :(

**Comment by mahboubii** [comment]
@klaszlo8207 thank you for reporting this, could you add more context to this?
1. are you in browser or node env?
2. which function/endpoint you have this issue with?

FYI, if you bump to v5, you can set custom time out. Also, we are now using Axios for network requests which could potentially solve your issue.

**Comment by mahboubii** [comment]
Closing this for the sake of housekeeping, in case you had more info let us know and we can reopen this issue.
