### ISSUE TITLE
TypeError: Cannot read property 'connect' of undefined

### ISSUE THREAD

**Issue by ellioseven** [GetStream/stream-js#451]
I'm attempting to connect to my API like so:

```ts
import stream from "getstream";

export const client = stream.connect(
  "xxx",
  "xxx",
  "xxx"
);

export const createUserToken = (userId: string) => {
  return client.createUserToken(userId);
};
```

However, I am getting the following:

```
node_1      | TypeError: Cannot read property 'connect' of undefined
node_1      |     at eval (webpack-internal:///./backend/stream/index.ts:7:65)
node_1      |     at Module../backend/stream/index.ts (/srv/.next/server/pages/api/graphql.js:366:1)
node_1      |     at __webpack_require__ (/srv/.next/server/pages/api/graphql.js:23:31)
node_1      |     at eval (webpack-internal:///./graphql/resolvers/query.ts:28:74)
node_1      |     at Module../graphql/resolvers/query.ts (/srv/.next/server/pages/api/graphql.js:618:1)
node_1      |     at __webpack_require__ (/srv/.next/server/pages/api/graphql.js:23:31)
node_1      |     at eval (webpack-internal:///./graphql/resolvers/index.ts:5:64)
node_1      |     at Module../graphql/resolvers/index.ts (/srv/.next/server/pages/api/graphql.js:594:1)
node_1      |     at __webpack_require__ (/srv/.next/server/pages/api/graphql.js:23:31)
node_1      |     at eval (webpack-internal:///./graphql/server.ts:7:68)
node_1      |     at Module../graphql/server.ts (/srv/.next/server/pages/api/graphql.js:642:1)
node_1      |     at __webpack_require__ (/srv/.next/server/pages/api/graphql.js:23:31)
node_1      |     at eval (webpack-internal:///./pages/api/graphql.ts:3:73)
node_1      |     at Module../pages/api/graphql.ts (/srv/.next/server/pages/api/graphql.js:654:1)
node_1      |     at __webpack_require__ (/srv/.next/server/pages/api/graphql.js:23:31)
node_1      |     at /srv/.next/server/pages/api/graphql.js:91:18
node_1      |     at Object.<anonymous> (/srv/.next/server/pages/api/graphql.js:94:10)
node_1      |     at Module._compile (internal/modules/cjs/loader.js:1137:30)
node_1      |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
node_1      |     at Module.load (internal/modules/cjs/loader.js:985:32)
node_1      |     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
node_1      |     at Module.require (internal/modules/cjs/loader.js:1025:19)
node_1      |     at require (internal/modules/cjs/helpers.js:72:18)
node_1      |     at DevServer.handleApiRequest (/srv/node_modules/next/dist/next-server/server/next-server.js:64:181)
node_1      |     at runMicrotasks (<anonymous>)
node_1      |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
node_1      |     at async Object.fn (/srv/node_modules/next/dist/next-server/server/next-server.js:56:492)
node_1      |     at async Router.execute (/srv/node_modules/next/dist/next-server/server/router.js:23:67)
node_1      |     at async DevServer.run (/srv/node_modules/next/dist/next-server/server/next-server.js:66:1042)
node_1      |     at async DevServer.handleRequest (/srv/node_modules/next/dist/next-server/server/next-server.js:34:504)
```

Am I instantiating this incorrectly? Can't seem to figure out what I'm doing wrong?

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/11637'>Zendesk ticket #11637</a>:<br><br>Hi

Thanks for reaching out to us.


    import { stream } from 'getstream';


_// or if you are on commonjs_


    const stream = require('getstream');


Cheers
Seetha<br><p><em><small>°°°</small></em></p>

**Comment by ellioseven** [comment]
Thanks for getting back to me so fast.

Doesn't seem like that export exists? I'm on `"getstream": "^7.2.9"`. I get the following:

```
TS2305: Module '"../../node_modules/getstream/lib"' has no exported member 'stream'.
```

The [documentation](https://getstream.io/activity-feeds/docs/node/?language=javascript) also states to use the default export, so not sure what do to?

**Comment by shodgetts** [comment]
Agent comment from Amin Mahboubi in <a href='https://getstream.zendesk.com/agent/tickets/11637'>Zendesk ticket #11637</a>:<br><br>Hi, please refer to the docs:

    import { connect } from 'getstream'; // or if you are on commonjs const { connect } = require('getstream'); // Instantiate new client with a user tokenconst client = connect('apikey', userToken, 'appid');<br><p><em><small>°°°</small></em></p>

**Comment by ellioseven** [comment]
@shodgetts Please see my comment above. There doesn't seem to be
