### ISSUE TITLE
Uncaught TypeError: axios.default.create is not a function

### ISSUE THREAD

**Issue by thecannabisapp** [GetStream/stream-js#560]
Hi, I've upgraded getstream from `getstream@7.4.1` to `getstream@8.1.5`, but now I'm getting all sorts of errors when I try to connect to the client.
```
Uncaught TypeError: axios.default.create is not a function
    at new StreamClient (client.js:220:1)
    at connect (connect.js:46:1)
```
Here's my React app code for setting up the client.
```typescript
import { StreamClient, connect } from "getstream";

const useCreateFeedClient = () => {
  const { STREAM_KEY, STREAM_APP_ID } = useConfig();
  const { data: streamToken } = useStreamTokenQuery();
  const [feed, setFeed] = useState<StreamClient>(undefined!);

  useEffect(() => {
    if (!streamToken) return;
    setFeed(connect(STREAM_KEY, streamToken.feed, STREAM_APP_ID));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [streamToken]);

  return feed;
};
```
What am I doing wrong here?

I noticed in 7.4.1 axios is 0.22, but on 8.1.5 axios is 1.4. I'm a bit puzzled. Here's my tsconfig.json just in case.
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
  },
  "include": [
    "src",
    "src/service-worker.ts"
  ]
}
```

**Comment by rlee1990** [comment]
I too am having the same errors

**Comment by rlee1990** [comment]
@JimmyPettersson85 can someone take a look into this?

**Comment by merapi** [comment]
I had to downgrade to make getstream work (clean-slate installation).

**Comment by xernobyl** [comment]
Hello. I'm looking into the issue. If you could provide me some more information about how you're using the SDK I would appreciate. From what I understood you're using it client side with react?
