### ISSUE TITLE
npm install error: Failed resolving git HEAD (git://github.com/matthisk/browser-request)

### ISSUE THREAD

**Issue by alexreedhill** [GetStream/stream-js#75]
Getting this issue when running npm install on version 3.0.0:

```
pm ERR! Failed resolving git HEAD (git://github.com/matthisk/browser-request) fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
npm ERR! Failed resolving git HEAD (git://github.com/matthisk/browser-request) Use '--' to separate paths from revisions, like this:
npm ERR! Failed resolving git HEAD (git://github.com/matthisk/browser-request) 'git <command> [<revision>...] -- [<file>...]'
npm ERR! Failed resolving git HEAD (git://github.com/matthisk/browser-request)
npm ERR! Failed resolving git HEAD (git@github.com:matthisk/browser-request) fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
npm ERR! Failed resolving git HEAD (git@github.com:matthisk/browser-request) Use '--' to separate paths from revisions, like this:
npm ERR! Failed resolving git HEAD (git@github.com:matthisk/browser-request) 'git <command> [<revision>...] -- [<file>...]'
npm ERR! Failed resolving git HEAD (git@github.com:matthisk/browser-request)
npm ERR! Error: No compatible version found: browser-request@'matthisk/browser-request'
npm ERR! Valid install targets:
npm ERR! ["0.1.0-beta1","0.1.0-beta2","0.1.0","0.2.0","0.2.1","0.3.0","0.3.1","0.3.2","0.3.3"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
```

**Comment by tbarbugli** [comment]
can you share your `package.json`?

**Comment by tbarbugli** [comment]
@matthisk any ideas what's going on here?

**Comment by matthisk** [comment]
@alexreedhill This probably has to do with your version of npm try updating to the last version (3.5) through `npm install -g npm` to fix your issue for now. I am investigating if we can avoid this issue in the future for people using npm 3.0.
